repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]

-   repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
    -   id: black

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    -   id: mypy
        args: ['--ignore-missing-imports', '--strict-equality', '--no-implicit-optional']
